namespace SchoolProject.Shared.Resources;

public static class SharedResourceKeys
{
    public static string Welcome = "Welcome";
    public static string NotFound = "NotFound";
    public static string DeletedSuccessfully = "DeletedSuccessfully";
    public static string AddedSuccessfully = "AddedSuccessfully";
    public static string CreatedSuccessfully = "CreatedSuccessfully";
    public static string UpdatedSuccessfully = "UpdatedSuccessfully";
    public static string SuccessfulOperation = "SuccessfulOperation";
    public static string Unauthorized = "Unauthorized";
    public static string BadRequest = "BadRequest";
    public static string Conflict = "Conflict";
    public static string UnprocessableEntity = "UnprocessableEntity";
    public static string NameRequired = "NameRequired";
    public static string NameTooLong = "NameTooLong";
    public static string RoleNameRequired = "RoleNameRequired";
    public static string RoleNameIsTooLong = "RoleNameIsTooLong";
    public static string RoleNameAlreadyExists = "RoleNameAlreadyExists";
    public static string RoleHasUsers = "RoleHasUsers";
    public static string NameArRequired = "NameArRequired";
    public static string NameArTooLong = "NameArTooLong";
    public static string NameArAlreadyInUse = "NameArAlreadyInUse";
    public static string NameEnRequired = "NameEnRequired";
    public static string NameEnTooLong = "NameEnTooLong";
    public static string NameEnAlreadyInUse = "NameEnAlreadyInUse";
    public static string UserNameRequired = "UsernameRequired";
    public static string UserNameInvalid = "UsernameInvalid";
    public static string UserNameTooLong = "UsernameTooLong";
    public static string UserNameAlreadyExist = "UsernameAlreadyExist";
    public static string UserNameAlreadyInUse = "UsernameAlreadyInUse";
    public static string EmailRequired = "EmailRequired";
    public static string EmailInvalid = "EmailInvalid";
    public static string EmailAlreadyExist = "EmailAlreadyExist";
    public static string EmailAlreadyInUse = "EmailAlreadyInUse";
    public static string EmailNotFound = "EmailNotFound";
    public static string PasswordRequired = "PasswordRequired";
    public static string PasswordMinimumLength = "PasswordMinimumLength";
    public static string PasswordRequireUppercase = "PasswordRequireUppercase";
    public static string PasswordRequireLowercase = "PasswordRequireLowercase";
    public static string PasswordRequireDigit = "PasswordRequireDigit";
    public static string PasswordRequireNonAlphanumeric = "PasswordRequireNonAlphanumeric";
    public static string ConfirmPasswordRequired = "ConfirmPasswordRequired";
    public static string PasswordsDoNotMatch = "PasswordsDoNotMatch";
    public static string PhoneRequired = "PhoneRequired";
    public static string PhoneTooLong = "PhoneTooLong";
    public static string PhoneInvalid = "PhoneInvalid";
    public static string AddressRequired = "AddressRequired";
    public static string AddressTooLong = "AddressTooLong";
    public static string CountryTooLong = "CountryTooLong";

    public static string InvalidUserNameOrPassword = "InvalidUserNameOrPassword";
    public static string EmailDoesNotConfirmed = "EmailDoesNotConfirmed";
    public static string EmailNotConfirmed = "EmailNotConfirmed";
    public static string PasswordResetCodeSentSuccessfully = "PasswordResetCodeSentSuccessfully";

    public static string RefreshTokenNotFound = "RefreshTokenNotFound";
    public static string RefreshTokenExpired = "RefreshTokenExpired";
    public static string RefreshTokenHasBeenRevoked = "RefreshTokenHasBeenRevoked";
    public static string EmailConfirmedSuccessfully = "EmailConfirmedSuccessfully";
    public static string SecurityException = "SecurityException";
    public static string LoggedOutSuccessfully = "LoggedOutSuccessfully";
    public static string RetrievedSuccessfully = "RetrievedSuccessfully";

    public static string DepartmentIdGreaterThanZero = "DepartmentIdGreaterThanZero";
    public static string DepartmentNotExist = "DepartmentNotExist";
    public static string DepartmentDoesNotExist = "DepartmentDoesNotExist";
    public static string SupervisorIdGreaterThanZero = "SupervisorIdGreaterThanZero";
    public static string SupervisorNotExist = "SupervisorNotExist";
    public static string RolesRequired = "RolesRequired";
    public static string SomeRolesNotExist = "SomeRolesNotExist";
    public static string IdRequired = "IdRequired";
    public static string IdGreaterThanZero = "IdGreaterThanZero";
    public static string NotExist = "NotExist";
    public static string PageNumberRequired = "PageNumberRequired";
    public static string PageNumberGreaterThanZero = "PageNumberGreaterThanZero";
    public static string PageSizeRequired = "PageSizeRequired";
    public static string PageSizeGreaterThanZero = "PageSizeGreaterThanZero";
    public static string InvalidPermissionClaims = "InvalidPermissionClaims";
    public static string InvalidEmailAddress = "InvalidEmailAddress";
    public static string EmailSentSuccessfully = "EmailSentSuccessfully";
    public static string SubjectTooLong = "SubjectTooLong";
    public static string Required = "Required";
    public static string InvalidOTP = "InvalidOTP";
    public static string InvalidUserId = "InvalidUserId";
    public static string ResetPasswordSuccessfully = "ResetPasswordSuccessfully";
}
