// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolProject.Infrastructure.Data;

#nullable disable

namespace SchoolProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429121814_Localize_Department_Name")]
    partial class Localize_Department_Name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "علوم الحاسوب",
                            NameEn = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "الرياضيات",
                            NameEn = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "الفيزياء",
                            NameEn = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "الكيمياء",
                            NameEn = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "الأحياء",
                            NameEn = "Biology"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.DepartmentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("DepartmentSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            DepartmentId = 1,
                            NameAr = "أحمد حسن",
                            NameEn = "Ahmed Hassan",
                            Phone = "01001234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            DepartmentId = 1,
                            NameAr = "فاطمة محمد",
                            NameEn = "Fatima Mohamed",
                            Phone = "01101234567"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Egypt",
                            DepartmentId = 2,
                            NameAr = "عمر علي",
                            NameEn = "Omar Ali",
                            Phone = "01201234567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo, Egypt",
                            DepartmentId = 2,
                            NameAr = "ليلى إبراهيم",
                            NameEn = "Layla Ibrahim",
                            Phone = "01001234568"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Helwan, Egypt",
                            DepartmentId = 3,
                            NameAr = "مصطفى كريم",
                            NameEn = "Mustafa Karim",
                            Phone = "01101234568"
                        },
                        new
                        {
                            Id = 6,
                            Address = "New Cairo, Egypt",
                            DepartmentId = 3,
                            NameAr = "أميرة حسن",
                            NameEn = "Amira Hassan",
                            Phone = "01201234568"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo, Egypt",
                            DepartmentId = 4,
                            NameAr = "خالد أحمد",
                            NameEn = "Khaled Ahmed",
                            Phone = "01001234569"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Giza, Egypt",
                            DepartmentId = 4,
                            NameAr = "نور صالح",
                            NameEn = "Noor Saleh",
                            Phone = "01101234569"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Cairo, Egypt",
                            DepartmentId = 5,
                            NameAr = "يوسف نصر",
                            NameEn = "Youssef Nasr",
                            Phone = "01201234569"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Helwan, Egypt",
                            DepartmentId = 5,
                            NameAr = "دينا خليل",
                            NameEn = "Dina Khalil",
                            Phone = "01001234570"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.StudentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 6,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 7,
                            StudentId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 8,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 9,
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 10,
                            StudentId = 5,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 11,
                            StudentId = 5,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 12,
                            StudentId = 6,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 13,
                            StudentId = 6,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 14,
                            StudentId = 7,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 15,
                            StudentId = 8,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 16,
                            StudentId = 9,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 17,
                            StudentId = 10,
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Data Structures",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Algorithms",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Web Development",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Calculus I",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Linear Algebra",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mechanics",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Name = "Electromagnetism",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Name = "Organic Chemistry",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Name = "Genetics",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.DepartmentSubject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.StudentSubject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
