// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolProject.Infrastructure.Data;

#nullable disable

namespace SchoolProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818102419_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 19,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 20,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "علوم الحاسوب",
                            NameEn = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "الرياضيات",
                            NameEn = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "الفيزياء",
                            NameEn = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "الكيمياء",
                            NameEn = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "الأحياء",
                            NameEn = "Biology"
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.DepartmentSubject", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("DepartmentSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            DepartmentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            DepartmentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            DepartmentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            DepartmentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            DepartmentId = 3,
                            SubjectId = 6
                        },
                        new
                        {
                            DepartmentId = 3,
                            SubjectId = 7
                        },
                        new
                        {
                            DepartmentId = 4,
                            SubjectId = 8
                        },
                        new
                        {
                            DepartmentId = 5,
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Identities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "a97a4913-dfc9-41b6-beba-aa2ba780c52d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "0731cd45-e921-4851-842d-7eaaa0ba7b40",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "2fd85377-76f7-489d-a723-e7656161415f",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Identities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "b1a89a8d-8b32-4946-bae5-334c2e11fdd2",
                            Email = "admin@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "المستخدم المسؤول",
                            NameEn = "Admin User",
                            NormalizedEmail = "ADMIN@YAHOO.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPEeEauhgQ1f/Kj6xJnhtrTrcQL5kvtLLOnz+LZLW0EFn64MoT7kLPSVGvfofF1A0w==",
                            PhoneNumber = "01001234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "0c2f2bc3-6e4d-4e94-aecb-32bae418d7c2",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            UserType = "Admin"
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Identities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_RefreshTokens_FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.InstructorSubject", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("InstructorSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            InstructorId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            InstructorId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            InstructorId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            InstructorId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            InstructorId = 14,
                            SubjectId = 4
                        },
                        new
                        {
                            InstructorId = 14,
                            SubjectId = 5
                        },
                        new
                        {
                            InstructorId = 15,
                            SubjectId = 4
                        },
                        new
                        {
                            InstructorId = 16,
                            SubjectId = 6
                        },
                        new
                        {
                            InstructorId = 16,
                            SubjectId = 7
                        },
                        new
                        {
                            InstructorId = 17,
                            SubjectId = 7
                        },
                        new
                        {
                            InstructorId = 18,
                            SubjectId = 8
                        },
                        new
                        {
                            InstructorId = 19,
                            SubjectId = 8
                        },
                        new
                        {
                            InstructorId = 20,
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.PasswordResetCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashedCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "HashedCode");

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("PasswordResetCodes");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 4,
                            SubjectId = 1,
                            Grade = 85.5m
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2,
                            Grade = 90.0m
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 3,
                            Grade = 78.0m
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 1,
                            Grade = 92.5m
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3,
                            Grade = 88.0m
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            Grade = 65.0m
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            Grade = 72.5m
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 4,
                            Grade = 81.0m
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 5,
                            Grade = 89.5m
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 6,
                            Grade = 95.0m
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 7,
                            Grade = 87.0m
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 6,
                            Grade = 74.5m
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 7,
                            Grade = 80.0m
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 8,
                            Grade = 83.0m
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 8,
                            Grade = 91.5m
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 9,
                            Grade = 77.0m
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 9,
                            Grade = 86.5m
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "هياكل البيانات",
                            NameEn = "Data Structures",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "الخوارزميات",
                            NameEn = "Algorithms",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "تطوير الويب",
                            NameEn = "Web Development",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "حسبان 1",
                            NameEn = "Calculus I",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "الجبر الخطي",
                            NameEn = "Linear Algebra",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            NameAr = "الميكانيكا",
                            NameEn = "Mechanics",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            NameAr = "الكهرومغناطيسية",
                            NameEn = "Electromagnetism",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            NameAr = "الكيمياء العضوية",
                            NameEn = "Organic Chemistry",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            NameAr = "علم الوراثة",
                            NameEn = "Genetics",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Views.DepartmentStudentsCountView", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_DepartmentStudentsCount", (string)null);
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Instructor", b =>
                {
                    b.HasBaseType("SchoolProject.Domain.Entities.Identities.ApplicationUser");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "a7c17b1a-33a4-48e5-9fd7-765421a99234",
                            Email = "teacher1@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. علي منصور",
                            NameEn = "Dr. Ali Mansour",
                            NormalizedEmail = "TEACHER1@YAHOO.COM",
                            NormalizedUserName = "TEACHER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "b719ecff-c01e-4641-a622-4150c4a3c274",
                            TwoFactorEnabled = false,
                            UserName = "teacher1",
                            UserType = "Instructor",
                            DepartmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "c9081a84-6af9-4469-ad9c-9ba72a9fca1d",
                            Email = "teacher2@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. سارة يوسف",
                            NameEn = "Dr. Sarah Youssef",
                            NormalizedEmail = "TEACHER2@YAHOO.COM",
                            NormalizedUserName = "TEACHER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01201234567",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a053d27a-715b-4af4-a5bc-660278dfd9ff",
                            TwoFactorEnabled = false,
                            UserName = "teacher2",
                            UserType = "Instructor",
                            DepartmentId = 1,
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "c9234567-1234-1234-1234-123456789012",
                            Email = "teacher3@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. كريم عادل",
                            NameEn = "Dr. Karim Adel",
                            NormalizedEmail = "TEACHER3@YAHOO.COM",
                            NormalizedUserName = "TEACHER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234573",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c9234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher3",
                            UserType = "Instructor",
                            DepartmentId = 2
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "ca234567-1234-1234-1234-123456789012",
                            Email = "teacher4@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. منى سمير",
                            NameEn = "Dr. Mona Samir",
                            NormalizedEmail = "TEACHER4@YAHOO.COM",
                            NormalizedUserName = "TEACHER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01201234573",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ca234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher4",
                            UserType = "Instructor",
                            DepartmentId = 2,
                            SupervisorId = 14
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "cb234567-1234-1234-1234-123456789012",
                            Email = "teacher5@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. طارق نجيب",
                            NameEn = "Dr. Tarek Naguib",
                            NormalizedEmail = "TEACHER5@YAHOO.COM",
                            NormalizedUserName = "TEACHER5",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01001234574",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cb234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher5",
                            UserType = "Instructor",
                            DepartmentId = 3
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "cc234567-1234-1234-1234-123456789012",
                            Email = "teacher6@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. نور فتحي",
                            NameEn = "Dr. Nour Fathy",
                            NormalizedEmail = "TEACHER6@YAHOO.COM",
                            NormalizedUserName = "TEACHER6",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234574",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cc234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher6",
                            UserType = "Instructor",
                            DepartmentId = 3,
                            SupervisorId = 16
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "cd234567-1234-1234-1234-123456789012",
                            Email = "teacher7@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. حنان عباس",
                            NameEn = "Dr. Hanan Abbas",
                            NormalizedEmail = "TEACHER7@YAHOO.COM",
                            NormalizedUserName = "TEACHER7",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01201234574",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cd234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher7",
                            UserType = "Instructor",
                            DepartmentId = 4
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "ce234567-1234-1234-1234-123456789012",
                            Email = "teacher8@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. يارا حامد",
                            NameEn = "Dr. Yara Hamed",
                            NormalizedEmail = "TEACHER8@YAHOO.COM",
                            NormalizedUserName = "TEACHER8",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01001234575",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ce234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher8",
                            UserType = "Instructor",
                            DepartmentId = 4,
                            SupervisorId = 18
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "cf234567-1234-1234-1234-123456789012",
                            Email = "teacher9@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "د. رانيا فاضل",
                            NameEn = "Dr. Rania Fadel",
                            NormalizedEmail = "TEACHER9@YAHOO.COM",
                            NormalizedUserName = "TEACHER9",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234575",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "cf234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "teacher9",
                            UserType = "Instructor",
                            DepartmentId = 5
                        });
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("SchoolProject.Domain.Entities.Identities.ApplicationUser");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "d910958e-d9b5-4ab8-bd90-6ba0645dcc13",
                            Email = "student1@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "أحمد حسن",
                            NameEn = "Ahmed Hassan",
                            NormalizedEmail = "STUDENT1@YAHOO.COM",
                            NormalizedUserName = "STUDENT1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01001234568",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "50729c87-1113-4c48-bbe4-80f88425eb01",
                            TwoFactorEnabled = false,
                            UserName = "student1",
                            UserType = "Student",
                            DepartmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "Giza, Egypt",
                            ConcurrencyStamp = "13c8aa62-fafb-4710-9341-7850c3f82868",
                            Email = "student2@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "فاطمة محمد",
                            NameEn = "Fatima Mohamed",
                            NormalizedEmail = "STUDENT2@YAHOO.COM",
                            NormalizedUserName = "STUDENT2",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234568",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a3ae62a1-4c23-480c-8049-f90c2334fad8",
                            TwoFactorEnabled = false,
                            UserName = "student2",
                            UserType = "Student",
                            DepartmentId = 1
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "Alexandria, Egypt",
                            ConcurrencyStamp = "c1234567-1234-1234-1234-123456789012",
                            Email = "student3@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "عمر علي",
                            NameEn = "Omar Ali",
                            NormalizedEmail = "STUDENT3@YAHOO.COM",
                            NormalizedUserName = "STUDENT3",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01201234570",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c1234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student3",
                            UserType = "Student",
                            DepartmentId = 2
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "c2234567-1234-1234-1234-123456789012",
                            Email = "student4@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "ليلى إبراهيم",
                            NameEn = "Layla Ibrahim",
                            NormalizedEmail = "STUDENT4@YAHOO.COM",
                            NormalizedUserName = "STUDENT4",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01001234571",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c2234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student4",
                            UserType = "Student",
                            DepartmentId = 2
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "Helwan, Egypt",
                            ConcurrencyStamp = "c3234567-1234-1234-1234-123456789012",
                            Email = "student5@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "مصطفى كريم",
                            NameEn = "Mustafa Karim",
                            NormalizedEmail = "STUDENT5@YAHOO.COM",
                            NormalizedUserName = "STUDENT5",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234571",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c3234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student5",
                            UserType = "Student",
                            DepartmentId = 3
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Address = "New Cairo, Egypt",
                            ConcurrencyStamp = "c4234567-1234-1234-1234-123456789012",
                            Email = "student6@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "أميرة حسن",
                            NameEn = "Amira Hassan",
                            NormalizedEmail = "STUDENT6@YAHOO.COM",
                            NormalizedUserName = "STUDENT6",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01201234571",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c4234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student6",
                            UserType = "Student",
                            DepartmentId = 3
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "c5234567-1234-1234-1234-123456789012",
                            Email = "student7@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "خالد أحمد",
                            NameEn = "Khaled Ahmed",
                            NormalizedEmail = "STUDENT7@YAHOO.COM",
                            NormalizedUserName = "STUDENT7",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01001234572",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c5234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student7",
                            UserType = "Student",
                            DepartmentId = 4
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            Address = "Giza, Egypt",
                            ConcurrencyStamp = "c6234567-1234-1234-1234-123456789012",
                            Email = "student8@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "نور صالح",
                            NameEn = "Noor Saleh",
                            NormalizedEmail = "STUDENT8@YAHOO.COM",
                            NormalizedUserName = "STUDENT8",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01101234572",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c6234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student8",
                            UserType = "Student",
                            DepartmentId = 4
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            Address = "Cairo, Egypt",
                            ConcurrencyStamp = "c7234567-1234-1234-1234-123456789012",
                            Email = "student9@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "يوسف نصر",
                            NameEn = "Youssef Nasr",
                            NormalizedEmail = "STUDENT9@YAHOO.COM",
                            NormalizedUserName = "STUDENT9",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01201234572",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c7234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student9",
                            UserType = "Student",
                            DepartmentId = 5
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            Address = "Helwan, Egypt",
                            ConcurrencyStamp = "c8234567-1234-1234-1234-123456789012",
                            Email = "student10@yahoo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NameAr = "دينا خليل",
                            NameEn = "Dina Khalil",
                            NormalizedEmail = "STUDENT10@YAHOO.COM",
                            NormalizedUserName = "STUDENT10",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgmuCLZWf94oa24FH2/rouApN2oGDwRIygAbVxhDGez79ryX8CUrYiJQarwvIpPPw==",
                            PhoneNumber = "01001234573",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "c8234567-1234-1234-1234-123456789012",
                            TwoFactorEnabled = false,
                            UserName = "student10",
                            UserType = "Student",
                            DepartmentId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Department", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Instructor", "Manager")
                        .WithOne()
                        .HasForeignKey("SchoolProject.Domain.Entities.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.DepartmentSubject", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Identities.RefreshToken", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.InstructorSubject", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.PasswordResetCode", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.StudentSubject", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("SchoolProject.Domain.Entities.Instructor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Domain.Entities.Instructor", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Student", b =>
                {
                    b.HasOne("SchoolProject.Domain.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Domain.Entities.Identities.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("SchoolProject.Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolProject.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
