// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolProject.Infrastructure.Data;

#nullable disable

namespace SchoolProject.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "علوم الحاسوب",
                            NameEn = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "الرياضيات",
                            NameEn = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "الفيزياء",
                            NameEn = "Physics"
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "الكيمياء",
                            NameEn = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "الأحياء",
                            NameEn = "Biology"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.DepartmentSubject", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("DepartmentSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            DepartmentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            DepartmentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            DepartmentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            DepartmentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            DepartmentId = 3,
                            SubjectId = 6
                        },
                        new
                        {
                            DepartmentId = 3,
                            SubjectId = 7
                        },
                        new
                        {
                            DepartmentId = 4,
                            SubjectId = 8
                        },
                        new
                        {
                            DepartmentId = 5,
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Identities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            NameAr = "د. علي منصور",
                            NameEn = "Dr. Ali Mansour"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            NameAr = "د. سارة يوسف",
                            NameEn = "Dr. Sarah Youssef",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            NameAr = "د. كريم عادل",
                            NameEn = "Dr. Karim Adel"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            NameAr = "د. منى سمير",
                            NameEn = "Dr. Mona Samir",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            NameAr = "د. طارق نجيب",
                            NameEn = "Dr. Tarek Naguib"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            NameAr = "د. نور فتحي",
                            NameEn = "Dr. Nour Fathy",
                            SupervisorId = 5
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            NameAr = "د. حنان عباس",
                            NameEn = "Dr. Hanan Abbas"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            NameAr = "د. يارا حامد",
                            NameEn = "Dr. Yara Hamed",
                            SupervisorId = 7
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            NameAr = "د. رانيا فاضل",
                            NameEn = "Dr. Rania Fadel"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.InstructorSubject", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("InstructorSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            InstructorId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            InstructorId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            InstructorId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            InstructorId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            InstructorId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            InstructorId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            InstructorId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            InstructorId = 5,
                            SubjectId = 6
                        },
                        new
                        {
                            InstructorId = 5,
                            SubjectId = 7
                        },
                        new
                        {
                            InstructorId = 6,
                            SubjectId = 7
                        },
                        new
                        {
                            InstructorId = 7,
                            SubjectId = 8
                        },
                        new
                        {
                            InstructorId = 8,
                            SubjectId = 8
                        },
                        new
                        {
                            InstructorId = 9,
                            SubjectId = 9
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            DepartmentId = 1,
                            NameAr = "أحمد حسن",
                            NameEn = "Ahmed Hassan",
                            Phone = "01001234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            DepartmentId = 1,
                            NameAr = "فاطمة محمد",
                            NameEn = "Fatima Mohamed",
                            Phone = "01101234567"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Egypt",
                            DepartmentId = 2,
                            NameAr = "عمر علي",
                            NameEn = "Omar Ali",
                            Phone = "01201234567"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo, Egypt",
                            DepartmentId = 2,
                            NameAr = "ليلى إبراهيم",
                            NameEn = "Layla Ibrahim",
                            Phone = "01001234568"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Helwan, Egypt",
                            DepartmentId = 3,
                            NameAr = "مصطفى كريم",
                            NameEn = "Mustafa Karim",
                            Phone = "01101234568"
                        },
                        new
                        {
                            Id = 6,
                            Address = "New Cairo, Egypt",
                            DepartmentId = 3,
                            NameAr = "أميرة حسن",
                            NameEn = "Amira Hassan",
                            Phone = "01201234568"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo, Egypt",
                            DepartmentId = 4,
                            NameAr = "خالد أحمد",
                            NameEn = "Khaled Ahmed",
                            Phone = "01001234569"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Giza, Egypt",
                            DepartmentId = 4,
                            NameAr = "نور صالح",
                            NameEn = "Noor Saleh",
                            Phone = "01101234569"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Cairo, Egypt",
                            DepartmentId = 5,
                            NameAr = "يوسف نصر",
                            NameEn = "Youssef Nasr",
                            Phone = "01201234569"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Helwan, Egypt",
                            DepartmentId = 5,
                            NameAr = "دينا خليل",
                            NameEn = "Dina Khalil",
                            Phone = "01001234570"
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            Grade = 85.5m
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            Grade = 90.0m
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            Grade = 78.0m
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            Grade = 92.5m
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            Grade = 88.0m
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4,
                            Grade = 65.0m
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 5,
                            Grade = 72.5m
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4,
                            Grade = 81.0m
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            Grade = 89.5m
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6,
                            Grade = 95.0m
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 7,
                            Grade = 87.0m
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6,
                            Grade = 74.5m
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 7,
                            Grade = 80.0m
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 8,
                            Grade = 83.0m
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 8,
                            Grade = 91.5m
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 9,
                            Grade = 77.0m
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 9,
                            Grade = 86.5m
                        });
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAr = "هياكل البيانات",
                            NameEn = "Data Structures",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            NameAr = "الخوارزميات",
                            NameEn = "Algorithms",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            NameAr = "تطوير الويب",
                            NameEn = "Web Development",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            NameAr = "حسبان 1",
                            NameEn = "Calculus I",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            NameAr = "الجبر الخطي",
                            NameEn = "Linear Algebra",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            NameAr = "الميكانيكا",
                            NameEn = "Mechanics",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            NameAr = "الكهرومغناطيسية",
                            NameEn = "Electromagnetism",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            NameAr = "الكيمياء العضوية",
                            NameEn = "Organic Chemistry",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            NameAr = "علم الوراثة",
                            NameEn = "Genetics",
                            Period = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Instructor", "Manager")
                        .WithOne()
                        .HasForeignKey("SchoolProject.Data.Entities.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.DepartmentSubject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Instructor", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolProject.Data.Entities.Instructor", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.InstructorSubject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Student", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.StudentSubject", b =>
                {
                    b.HasOne("SchoolProject.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolProject.Data.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolProject.Data.Entities.Instructor", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
